# Generated by Django 5.0.1 on 2024-01-25 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ihaalls',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ihaName', models.CharField(max_length=50)),
                ('serialNo', models.CharField(max_length=50)),
                ('yearOfProduction', models.DateField()),
                ('numbers', models.IntegerField()),
                ('monthOfee', models.FloatField()),
                ('currency', models.CharField(default='TL', max_length=40)),
                ('rentalActive', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Admin', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ihainformation',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('rentmonth', models.IntegerField()),
                ('rentcurrency', models.CharField(max_length=50)),
                ('item', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('currency', models.CharField(default='TL', max_length=40)),
                ('rentalPeriodOver', models.BooleanField(default=False)),
                ('rentihaid', models.ForeignKey(limit_choices_to={'rentalActive': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentiha.ihaalls')),
            ],
        ),
    ]
